# Generated by Django 3.1 on 2020-08-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dummy_stuff', models.CharField(max_length=10, verbose_name='dummy')),
            ],
            options={
                'db_table': '临时DB',
            },
        ),
    ]
